apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-chat
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: frontend-deployment-frontend-80
          servicePort: 80
      - path: /chat
        backend:
          serviceName: backend-deployment-backend-80
          servicePort: 80