apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-chat
spec:
  rules:
  - host: my.kubernetes.example
    http:
      paths:
      - path: /chat
        backend:
          serviceName: backend-svc
          servicePort: 80
      - backend:
          serviceName: frontend-svc
          servicePort: 80
